config/routes.rb
Rails.application.routes.draw do
  resources :tclones do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tclone.rb
class Tclone < ApplicationRecord
  validates :content, length: {in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tclones_controller.rb
class TclonesController < ApplicationController
  before_action :find_tclone , only: [:edit, :update, :destroy]
  def index
    @tclones = Tclone.all
  end

  def new
    @tclone = Tclone.new
  end

  def create
    @tclone = Tclone.new(tclone_params)
    if params[:back]
      render :new
    else
      if @tclone.save
        redirect_to tclones_path, notice: "ツイートを追加しました"
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    if @tclone.update(tclone_params)
      redirect_to tclones_path, notice: "ツイートを編集しました"
    else
      render :edit
    end
  end

  def destroy
    @tclone.destroy
    redirect_to tclones_path, notice: "ツイートを削除しました"
  end

  def confirm
    @tclone = Tclone.new(tclone_params)
    render :new if @tclone.invalid?
  end

  private
  def tclone_params
    params.require(:tclone).permit(:content)
  end

  def find_tclone
    @tclone = Tclone.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tclones_helper.rb
module TclonesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_tclones_path
    elsif action_name == 'edit'
      tclone_path

    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tclones/_form.html.erb
<%= form_with(model: @tclone, local: true, url: choose_new_or_edit) do |form| %>
<%# このurlはhelperメソッドに記載してます。helperメソッドは全てのviewから参照が可能なファイルです %>
  <% if @tclone.errors.any? %>
    <div id="error_explanation" >
      <h2><%= @tclone.errors.count %>件のエラーがあります</h2>
      <ul>
        <% @tclone.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="tweet_content">
    <p><%= form.label :content %></p>
    <p><%= form.text_area :content, size: "70x10" %></p>
  </div>
  <%= form.submit %>
<% end %>

<p><%= link_to 'ツイート一覧画面へ', tclones_path %></p>

app/views/tclones/confirm.html.erb
<h2>ツイート編集</h2>
<%= form_with(model: @tclone, local: true,) do |form| %>
  <div class="tweet_content">
    <%= form.hidden_field :content %>
    <p>内容：<%= @tclone.content %></p>
  </div>
  <%= form.submit "投稿する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

<p><%= link_to 'ツイート一覧画面へ', tclones_path %></p>

app/views/tclones/edit.html.erb
<h2>ツイート編集</h2>

<%= render 'form' %>

app/views/tclones/index.html.erb
<div class="container">
  <header class="header">
    <a class="header_left">Twitterクローン</a>
    <%= link_to 'ツイート画面へ', new_tclone_path, class: "header_right"%>

  </header>

  <div class="index_container">
    <h2>ツイート一覧</h2>
    <% @tclones.each do |tclone| %>
    <div class="tweet">
      <p id="content"><%= tclone.content %></p>
      <ul>
        <li><%= link_to 'ツイートを編集', edit_tclone_path(tclone.id) %></li>
        <li><%= link_to 'ツイートを削除', tclone_path(tclone.id), method: :delete %></li>
      </ul>
    </div>
    <% end %>
  </div>

  <footer class="footer">
    <p>2020年01月期　松原弘樹　Ruby on Rails入門シリーズ課題【TwitterClone】</p>
  </footer>

</div>

app/views/tclones/new.html.erb
<h2>新規ツイート</h2>
<%= render 'form' %>